/** 日本語マッピング定数（score_artifacts.py より移植） */

import type { ArtifactSlotKey, StatKey } from './types'

export const ARTIFACT_SET_NAMES: Record<string, string> = {
  ADayCarvedFromRisingWinds: '風立ちの日',
  Adventurer: '冒険者',
  ArchaicPetra: '悠久の磐岩',
  AubadeOfMorningstarAndMoon: '暁の星と月の歌',
  Berserker: '狂戦士',
  BlizzardStrayer: '氷風を彷徨う勇士',
  BloodstainedChivalry: '血染めの騎士道',
  BraveHeart: '勇士の心',
  CrimsonWitchOfFlames: '燃え盛る炎の魔女',
  DeepwoodMemories: '深林の記憶',
  DefendersWill: '守護の心',
  DesertPavilionChronicle: '砂上の楼閣の史話',
  EchoesOfAnOffering: '来歆の余響',
  EmblemOfSeveredFate: '絶縁の旗印',
  FinaleOfTheDeepGalleries: '深廊の終曲',
  FlowerOfParadiseLost: '楽園の絶花',
  FragmentOfHarmonicWhimsy: '諧律奇想の断章',
  Gambler: '博徒',
  GildedDreams: '金メッキの夢',
  GladiatorsFinale: '剣闘士のフィナーレ',
  GoldenTroupe: '黄金の劇団',
  HeartOfDepth: '沈淪の心',
  HuskOfOpulentDreams: '華館夢醒形骸記',
  Instructor: '教官',
  Lavawalker: '烈火を渡る賢者',
  LongNightsOath: '長き夜の誓い',
  LuckyDog: '幸運',
  MaidenBeloved: '愛される少女',
  MarechausseeHunter: 'ファントムハンター',
  MartialArtist: '武人',
  NightOfTheSkysUnveiling: '天穹の顕現せし夜',
  NighttimeWhispersInTheEchoingWoods: '残響の森で囁かれる夜話',
  NoblesseOblige: '旧貴族のしつけ',
  NymphsDream: '水仙の夢',
  ObsidianCodex: '黒曜の秘典',
  OceanHuedClam: '海染硨磲',
  PaleFlame: '蒼白の炎',
  PrayersForDestiny: '水祭りの人',
  PrayersForIllumination: '火祭りの人',
  PrayersForWisdom: '雷祭りの人',
  PrayersToSpringtime: '氷祭りの人',
  ResolutionOfSojourner: '旅人の心',
  RetracingBolide: '逆飛びの流星',
  Scholar: '学者',
  ScrollOfTheHeroOfCinderCity: '灰燼の都に立つ英雄の絵巻',
  ShimenawasReminiscence: '追憶のしめ縄',
  SilkenMoonsSerenade: '月を紡ぐ夜の歌',
  SongOfDaysPast: '在りし日の歌',
  TenacityOfTheMillelith: '千岩牢固',
  TheExile: '亡命者',
  ThunderingFury: '雷のような怒り',
  Thundersoother: '雷を鎮める尊者',
  TinyMiracle: '奇跡',
  TravelingDoctor: '医者',
  UnfinishedReverie: '遂げられなかった想い',
  VermillionHereafter: '辰砂往生録',
  ViridescentVenerer: '翠緑の影',
  VourukashasGlow: '花海甘露の光',
  WanderersTroupe: '大地を流浪する楽団',
}

export const SLOT_NAMES: Record<ArtifactSlotKey, string> = {
  flower: '生の花',
  plume: '死の羽',
  sands: '時の砂',
  goblet: '空の杯',
  circlet: '理の冠',
}

export const STAT_NAMES: Record<StatKey, string> = {
  hp: 'HP',
  atk: '攻撃力',
  def: '防御力',
  hp_: 'HP%',
  atk_: '攻撃力%',
  def_: '防御力%',
  enerRech_: '元素チャージ効率',
  eleMas: '元素熟知',
  critRate_: '会心率',
  critDMG_: '会心ダメージ',
}

/** パーセント表記のサブステ */
export const PERCENT_STATS = new Set<StatKey>([
  'hp_',
  'atk_',
  'def_',
  'enerRech_',
  'critRate_',
  'critDMG_',
])
